GuitarShop/GuitarShop/GuiShop/urls.py
from django.urls import path
from GuiShop.views import *
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from cart.views import *

urlpatterns = [
    path('index/<slug:cat_slag>/', RenderIndex, name='category'),
    path("product/<slug:post_slug>/", RenderProduct, name='product'),
    path("cart/", cart_detail, name='cart')

]
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GuitarShop/GuitarShop/GuitarShop/urls.py
from django.contrib import admin
from django.urls import path, include
from GuiShop.views import wiew_home
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('orders.urls', namespace='orders')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('gushop/', include("GuiShop.urls")),
    path('', wiew_home, name='home')
]

GuitarShop/GuitarShop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

GuitarShop/GuitarShop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

GuitarShop/GuitarShop/GuiShop/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    avatar = models.ImageField(upload_to='gallery', null=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_last_image(self):
        try:
             last_image = self.images.last().image
        except AttributeError:
             last_image = self.image



class Gallery(models.Model):
    image = models.ImageField(upload_to='gallery')

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')

GuitarShop/GuitarShop/cart/models.py
from django.db import models

GuitarShop/GuitarShop/orders/models.py
from django.db import models
from GuiShop.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

GuitarShop/GuitarShop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

GuitarShop/GuitarShop/orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

GuitarShop/GuitarShop/GuiShop/views.py
from django.shortcuts import render
from GuiShop.models import *
from django.shortcuts import get_object_or_404
from cart.forms import CartAddProductForm
# Create your views here.
def RenderIndex(request, cat_slag):
    if request.method == "POST":
        name_of_product = request.POST.get("searchform")
        images = Gallery.objects.all()
        context = {
            "categories": Category.objects.all,
            "products": Product.objects.filter(name__startswith=name_of_product),
            "images": images
        }
        return render(request, 'index.html', context)
    if cat_slag == "all":
        images = Gallery.objects.all()
        context = {
            "categories": Category.objects.all,
            "products": Product.objects.all,
            "images": images

        }
        return render(request, 'index.html', context)
    else:
        images = Gallery.objects.all()
        category = get_object_or_404(Category, slug=cat_slag)
        products = Product.objects.filter(category=category.id)
        context = {
            "categories": Category.objects.all,
            "products": products,
            "images": images

        }
        return render(request, 'index.html', context)

def RenderProduct(request, post_slug):
    product = get_object_or_404(Product, slug=post_slug)
    cart_product_form = CartAddProductForm()
    context = {'product':product,
               'cart_product_form':cart_product_form,}

    return render(request, 'product.html', context)

def wiew_home(request):
    return RenderIndex(request, 'all')

def Render_aboutus(request):
    pass

GuitarShop/GuitarShop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from GuiShop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

GuitarShop/GuitarShop/orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})

GuitarShop/GuitarShop/GuitarShop/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GuitarShop</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
</head>
<body>
 <header class="header">

        <h1><a id="site_logo" href="index.html">Guitar Shop</a></h1>

        <ul class="nav">
            <li class="categoryitem"><a href="{% url 'category' 'all'%}">Home</a></li>
            <li class="categoryitem"><a href="{%  url 'cart' %}">Shopping Cart</a></li>

        </ul>

        <form action="" method="post" class="search" >
            {% csrf_token %}
            <input type="search" name="searchform" placeholder="search" class="input" />
            <input type="submit" name="" value="" class="submit" />
        </form>

        <ul  class="nav" >
            {% for category in categories%}
            <li  class="categoryitem"><a href="{% url 'category' category.slug %}" >{{category.name}}</a></li>
            {% endfor %}
        </ul>

    </header>
    <div class="container_1">
        <ul>
            {% for product in products%}
                <li  class="product_item">
                    <a href="{% url 'product' product.slug %}" class="product">

                        <div class="product-photo">

                            <img src="{% static product.avatar.url %}">

                    </div>

                        {{product.name}}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

GuitarShop/GuitarShop/GuitarShop/templates/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GuitarShop</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
</head>
<body>
 <header class="header">

        <h1><a id="site_logo" href="index.html">Guitar Shop</a></h1>

        <ul class="nav">
            <li class="categoryitem"><a href="{% url 'category' 'all'%}">Home</a></li>
            <li class="categoryitem"><a href="{%  url 'cart' %}">Shopping Cart</a></li>

        </ul>




    </header>

 <div class="product_">
     <ul>
     {% for image in product.images.all %}
         <li  class="product_item">
        <div class="product-photo" >
            <img src="{% static image.image.url%}">
        </div>
         </li>
     {% endfor %}
     </ul>
    <h1>{{product.name}}</h1>
     
     <p>{{product.description}}</p>
     <p>{{product.price}}</p>
 </div>
 <form action="{% url 'cart:cart_add' product.id %}" method="post">
     {{ cart_product_form }}
     {% csrf_token %}
     <input type="submit" value="Add to cart">
 </form>
</body>
</html>

GuitarShop/GuitarShop/GuitarShop/templates/regestration/log_in.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

GuitarShop/GuitarShop/GuitarShop/templates/regestration/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

GuitarShop/GuitarShop/cart/templates/cart/detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
<header class="header">

        <h1><a id="site_logo" href="index.html">Guitar Shop</a></h1>

        <ul class="nav">
            <li class="categoryitem"><a href="{% url 'category' 'all'%}">Home</a></li>
            <li class="categoryitem"><a href="{%  url 'cart' %}">Shopping Cart</a></li>

        </ul>

</header>
{% block content %}
  <h1>Shopping cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Avatar</th>
        <th>Product</th>
        <th>Reload value</th>
        <th>delete</th>
        <th>value</th>
        <th>price</th>
        <th>all price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <div class="product_item">
                  <div class="product-photo">
                <img src="{% if product.avatar %}{% static product.avatar.url %}{% endif %}">
                  </div>
                  </div>
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Reload">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Delete</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>All price</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">

    <a href="{% url "orders:order_create" %}" class="button">
    Checkout
    </a>
  </p>
{% endblock %}

GuitarShop/GuitarShop/orders/templates/orders/order/create.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
<header class="header">

        <h1><a id="site_logo" href="index.html">Guitar Shop</a></h1>

        <ul class="nav">
            <li class="categoryitem"><a href="{% url 'category' 'all'%}">Home</a></li>
            <li class="categoryitem"><a href="{%  url 'cart' %}">Shopping Cart</a></li>

        </ul>

</header>
{% block content %}
    <h1>Checkout</h1>
    <div class="order-info">
        <h3>Your order</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Total: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Place order"></p>
        {% csrf_token %}
    </form>
{% endblock %}

GuitarShop/GuitarShop/orders/templates/orders/order/created.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "css/index.css" %}">
{% block title %}Thank you{% endblock %}
<header class="header">

        <h1><a id="site_logo" href="index.html">Guitar Shop</a></h1>

        <ul class="nav">
            <li class="categoryitem"><a href="{% url 'category' 'all'%}">Home</a></li>
            <li class="categoryitem"><a href="{%  url 'cart' %}">Shopping Cart</a></li>

        </ul>

</header>
{% block content %}
    <h1>Thank you</h1>
    <p>Your order has been successfully completed. Your order number is
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}